### ISSUE TITLE
Cannot read property "includes" of undefined

### ISSUE THREAD

**Issue by andybee** [architect/sandbox#102]
The Sandbox HTTP server middleware assumes that a POST or PUT request will always have a `Content-Type` header. If sent without, the response is an Internal Server Error which includes the stack trace:

```
TypeError: Cannot read property "includes" of undefined
  at type (node_modules/@architect/sandbox/src/http/index.js:35:44)
```

**Steps to reproduce**
1. Create an HTTP POST or PUT function.
2. Run `arc sandbox`
3. Call the related method and path on localhost with a request that excludes a 'Content-Type' header.

**Expected behavior**
Whilst these types of request *should* contain a Content-Type header, I would expect the server to still call the function without an Internal Server Error.

**Comment by andybee** [comment]
The stack trace points to the URL encoded middleware, where it calls `.includes` on the result of the `content-type` key in the headers dictionary. If the header doesn't exist, it returns undefined, and the test fails.

**Comment by ryanblock** [comment]
Word, we should be flexible with that. Will take a look at that today while I'm in the guts of sandbox. (Workaround would be, ofc, to include a content-type header; per spec, POSTs etc. [should](https://tools.ietf.org/html/rfc2119#section-3) include that header.)

**Comment by andybee** [comment]
Yep, I'm working around it, but took a while to work out why I was getting 500s deep inside an obscure HTTP call.

I've done a PR #103 with a quick fix, though appreciate you might want to find a more elegant solution.

**Comment by ryanblock** [comment]
Fix now in master queued to go out with the next release. Thanks again @andybee!
