### ISSUE TITLE
Is it possible to run sandbox with @static pragma that won't apply any cache-control headers?

### ISSUE THREAD

**Issue by andybee** [architect/sandbox#112]
I'm working on a project which has a small amount of client-side JS which I'm hosting via @static pragma.

Because Architect (rightly) sets `cache-control` headers for static assets, it makes dev a bit painful on this JS code as changes won't easily appear in the browser without doing hard refreshes.

I checked the documentation and couldn't find it mentioned, but I wondered if there's a flag or setting so I can run sandbox in a development mode that prevents it setting cache-control headers? If not, could it be considered as a future feature?

**Comment by ryanblock** [comment]
If you need to set custom cache-control headers for your static assets, you'll need to run the proxy manually. Fortunately, that's pretty easy:
1. Add: `get /` to your `@http` pragma
2. Install `@architect/functions` to `src/http/get-index/package.json`
3. Make this your `index.js`:
```
let arc = require('@architect/functions')
let cacheControl
if (node_env === 'testing') cacheControl = 'no-cache, no-store, must-revalidate, max-age=0, s-maxage=0'
exports.handler = arc.http.proxy({cacheControl})
```

**Comment by andybee** [comment]
That works, but is there a neat way I can then mark that HTTP route to not be deployed?

Feels a bit wasteful to have a Lambda function deployed that does the same thing as a standard S3 asset.

**Comment by ryanblock** [comment]
It's def not wasteful – actually, I think it's super fast, efficient, and effective. Something has to deliver the root route – if you don't specify `get /`, we'll create, manage, and auto-configure a Lambda to do under the hood. The above technique is effectively the same architecture as what you already had, except it allows you to pass your own custom configuration.

**Comment by andybee** [comment]
Thanks for clarification, I wasn’t aware that was how it worked under the hood. For reason I’d assumed it configured the API Gateway to route to the S3 bucket.

**Comment by ryanblock** [comment]
Not too far off! That is indeed how it works if you specify `@static` but do not specify `@http`.

**Comment by andybee** [comment]
<the-more-you-know.gif> ✨
