### ISSUE TITLE
Seeding sandbox @tables

### ISSUE THREAD

**Issue by andybee** [architect/sandbox#117]
Can't find anything in the docs, but wondering if there is a built-in way to seed a `@tables` DB when you bring the sandbox up?

e.g. I could place a .json file somewhere and when I launch the sandbox it populates the in-memory datastore accordingly?

**Comment by ryanblock** [comment]
Close! In `1.4.0` we introduced init script support!
  - `sandbox` will now run the init script of your choosing upon startup after all subsystems have started up:
    - `scripts/sandbox-startup.js` - a CommonJS module, receives your parsed Arc project as a parameter, supports async/await
    - `scripts/sandbox-startup.py` - a Python script
    - `scripts/sandbox-startup.rb` - a Ruby script

With this, you could read out of a JSON file and write a small script to write that directly into Dynamo.

**Comment by andybee** [comment]
Perfect! Apologies if I missed this somewhere.

**Comment by ryanblock** [comment]
Considering it in beta rn awaiting feedback... it's not formally documented yet, just in the changelog.

**Comment by andybee** [comment]
Implemented in my project now and works great! +1 for the feature from me, thanks!
