### ISSUE TITLE
reconfigure source folder

### ISSUE THREAD

**Issue by brianleroux** [architect/sandbox#122]
https://github.com/brianleroux/arc-example-macro demonstrates rewriting the Lambda CodeUri property of the generated CloudFormation. This technique would work for any compile-to-js solution. Elm. CoffeeScript. BabelScript. Etc. 

The problem with this technique is the higher level language would not successfully execute in the sandbox. One possible fix is to teach the sandbox about the code paths (similar to how we are modifying the paths with the macro). We currently support `folder` property under `@static`. We could add a new pragma (cringe) named `@sandbox` and give it a `folder` property. Like so:

```
@app
myapp

@sandbox
folder dist

@http
get /
get /foo

@macro
coffeescript 
```

**Comment by ryanblock** [comment]
Couple ideas (order of pref):
- Make that part of the `@app` config
- `@local` or `@localDev` instead of `@sandbox`

**Comment by darbio** [comment]
Just another workaround: I currently have typescript working without needing any new pragmas. I add an `index.ts` in the folder and then use `tsc` to build (and overwrite) the `index.js` when I `yarn start`. I don't commit `index.js` to source.

This is my `tsconfig`:

```
{
    "compileOnSave": true,
    "compilerOptions": {
        "module": "commonjs",
        "baseUrl": "src",
        "sourceMap": true,
        "declaration": false,
        "moduleResolution": "node",
        "emitDecoratorMetadata": true,
        "experimentalDecorators": true,
        "esModuleInterop": true,
        "target": "es2017",
        "typeRoots": ["node_modules/@types"],
        "lib": ["es2017", "dom"]
    }
}
```

**Comment by brianleroux** [comment]
this works! also we now support Deno =)
