### ISSUE TITLE
remove http middleware from sandbox http server to align with lambda

### ISSUE THREAD

**Issue by filmaj** [architect/sandbox#14]
all this stuff probably needs to get axed, and instead moved to functions (see architect/functions#43): https://github.com/architect/sandbox/blob/master/src/http/index.js#L17-L29

(except maybe binary, dunno)

otherwise you might be getting json and body parsing for 'free' when playing around in sandbox, then when you go to deploy, uh oh, none of that works anymore.

**Comment by ryanblock** [comment]
I believe this issue is no longer valid; it now includes a `!req.isBase64Encoded` predicate, which means that for Arc 6+ projects, there won't be a behavioral delta between sandbox and live infra.
