### ISSUE TITLE
WS Lambda Not Found displayed when no custom routes found 

### ISSUE THREAD

**Issue by pchinjr** [architect/sandbox#228]
**Describe the issue**
When using WebSockets in sandbox, every call to $default will print Websocket Lambda not found, invoking ws/default from https://github.com/architect/sandbox/blob/d971111f2fd6f672a33fc2adb64f2b1dd0682cd6/src/http/register-websocket.js#L73

**Steps to reproduce**
use arc-example-ws repo, npm i, and arc sandbox. Then type a message and broadcast it. 

**Expected behavior**
the line printed should not show up unless calling a custom expression route that doesn't exist 

**Screenshots**
N/A

**Desktop**
Please complete the following information (if appropriate):
 - OS: MacOS
 - Browser: Chrome
 - arc 6.1.5 sandbox 1.5.7

**Comment by ryanblock** [comment]
Hmm, unless I'm mistaken I don't think that's a bug, it's more informational. It's intent is to let the user know that a specific WS handler wasn't defined when the message was passed, and thus it's being handled by `ws/default`.

The idea of a "default" handler is a bit strange – that said, we don't do the same thing for HTTP where `get /` handles all requests that aren't defined in the Architect project manifest. So I can see shoring this up to be more consistent!

**Comment by pchinjr** [comment]
It could say, no specific action in the request body found, so invoking $default handler.

**Comment by ryanblock** [comment]
Will be fixed in the next release!
