### ISSUE TITLE
scheduled events not firing on sandbox

### ISSUE THREAD

**Issue by mikemaccana** [architect/sandbox#23]
Per https://github.com/architect/arc.codes/blob/master/src/shared/en/aws/reference-scheduled.md I have a `scheduled` item called `rates` in `.arc`:

```
@scheduled
stats rate(1 minute)
```

I couldn't find an example but there's one in https://github.com/architect/architect/blob/master/test/slow/hydrate/mock/app/src/scheduled/hikes-with-friends/index.js, so using that as a template:

```
let arc = require('@architect/functions')

async function handler(event, callback) {
  console.log(`______________________________________________`)
  console.log(JSON.stringify(event, null, 2))
  callback()
}

exports.handler = arc.scheduled(handler)
```

However no `console.log`s are printed.

**Comment by ryanblock** [comment]
Valid issue, although not new – `sandbox` has never supported `@scheduled`. But it should!

**Comment by brianleroux** [comment]
I suppose we could honor the scheduled expression and just go with it…always felt a bit dangerous to me and unsure how hard parsing/logic will be to get scheduled expression invocation working. But I'm into it. How would we handle: `weekly-email rate(1 week)` ? Or even an hourly cron expression that only fired on the third wed of the month? Just don't fire if it isn't that day?

When we author these things we unit tested them in isolation. I'm curious: what are you doing on that 1 minute interval @mikemaccana ?

**Comment by ryanblock** [comment]
A maybe-stupid idea: while sandbox is running in CLI what if we look for a user input (say, `sched`) that invokes all scheduled functions?

**Comment by ryanblock** [comment]
Closing issue due to lack of consensus on solution and interest. Let's reopen if anyone wants to reengage on this though!

**Comment by darbio** [comment]
I'm interested in this functionality. I have a use case where I need to poll an RSS feed every 30 minutes. It would be great to be able to test this locally.

Not so sure about waiting for user input though. It would be better to honour the rates in the `.arc` file. Could be implemented using `setInterval` fairly trivially by parsing the `rate(x minutes)` or cron format (e.g. [cron-parser](https://www.npmjs.com/package/cron-parser)).

**Comment by grahamb** [comment]
I'm also interested in this functionality. The use case I'm working with right now is a scheduled function that fires at an interval (`rate(1 minute)`) to fetch data from an API and cache it for later retrieval by a HTTP function. I can test the HTTP function in the sandbox, but not the scheduled function. This use case it simple enough that I can work around it by using `arc repl` to seed some data for testing, but that's not ideal.

I can see the argument for cron'd functions being harder to support, but the rate ones should be fairly straightforward, I'd think.

**Comment by ryanblock** [comment]
Right on. Realistically, I'm not going to get to working on this this month or possibly this year, but happy to provide some guidance on where / how to start if anyone wants to get a PR cooking.

**Comment by grahamb** [comment]
I'd be willing to take a shot at it; guidance would be appreciated, especially on any pitfalls you or @brianleroux might have come across.

**Comment by grahamb** [comment]
In the meantime, this works 😆

```js
const { handler } = require('./src/scheduled/fetch-ga-data/index.js');

const main = async () => {
  await handler();
  setInterval(async () => {
    await handler();
  }, 60000);
};

main();
```
