### ISSUE TITLE
Recently sandbox no longer serves static assets

### ISSUE THREAD

**Issue by filmaj** [architect/sandbox#25]
I think since #15 was merged, this no longer works when I upgraded from cli 6.0.20 to 6.0.28, which moved sandbox from v1.2.2 to v1.2.9.

I have both a `GET /` route defined as well as stuff in the `public/` folder that I'm expecting be served at `/_static`. Instead, all static content is getting served the `GET /` route.

My `.arc` file:

```
@app
arctonic

@aws
region us-west-2
profile default
bucket arctonic

@domain
arcandtonic.technology

@static
ignore
  eslint

@http
get /
# API
post /api/signup
post /api/login
post /api/logout
post /api/notes
get  /api/notes
post /api/notes/:noteID/del

@tables
accounts
  accountID *String

notes
  accountID *String
  noteID **String
```

**Comment by ryanblock** [comment]
Apologies, I duplicated this issue here: https://github.com/architect/architect/issues/416

I also issued a quick fix before I'd seen this, but let's still merge yours as well, as it's better (includes testing, etc. – thank you!).
