### ISSUE TITLE
Sandbox: post-startup script queue / plugins

### ISSUE THREAD

**Issue by boldenburg** [architect/sandbox#32]
### Feature

Add a mechanism to allow pre-populating data when running `npx sandbox`

### Use case

I'd like to be able to specify a variety of starting states for my app (so effectively for the datastore) and pick one when I run `npx sandbox` for simulation / user interaction testing

### Acceptance criteria

`npx sandbox` has an optional flag that specifies the starting state with which to initialize the database

**Comment by ryanblock** [comment]
I'd like to slightly increase the scope of this issue: ideally Sandbox should have a basic post-startup script queue caller that accepts any number of plugin scripts to run post execution; that may include pre-populated data to be injected into the database, or build scripts, etc.

**Comment by ryanblock** [comment]
This feature is now in `1.4.0` RC! Changelog summary:
- Beta: `sandbox` init script support!
  - `sandbox` will now run the init script of your choosing upon startup after all subsystems have started up:
    - `scripts/sandbox-startup.js` - a CommonJS module, receives your parsed Arc project as a parameter, supports async/await
    - `scripts/sandbox-startup.py` - a Python script
    - `scripts/sandbox-startup.rb` - a Ruby script

You should be able to do just about anything with this, but please feel free to (re)open this or a new issue with additional use cases / feature requests.
