### ISSUE TITLE
HTTPS with sandbox

### ISSUE THREAD

**Issue by aAmitSengar** [architect/sandbox#34]
How can i run sendbox with HTTPS?

**Comment by aAmitSengar** [comment]
Ok thanks.

**Comment by ryanblock** [comment]
We've discussed quite a bit, but we don't presently have a use case, and the challenges of making the cert process simple is a high hurdle.

Closing for now, but this issue remains on our radar. Discussion would be accelerated by specific use cases of HTTPS in the local dev env!

**Comment by darbio** [comment]
The most compelling and low level use case for using HTTPS locally is that it mimics production more closely - with all the goodness that comes with that.

An example where this would be good is when setting cookies: currently on sandbox `secure` cookies cannot be used, however they can (and should) be used in production.

Obviously a lower priority than other issues but a use-case none the less.
