### ISSUE TITLE
Sandbox start.js has a async issue (will fail reading file, then continue on regardless)

### ISSUE THREAD

**Issue by mikemaccana** [architect/sandbox#39]
**Describe the issue**

An arc 6 RC2, hello world, using a JSON arc manifest, on Windows
```
√ Found Architect manifest, starting up
Sandbox error! No Architect manifest found, cannot start
```

This is from `start.js` in manifest. Obviously the messages shouldn't both be displayed, so there's some duplicate logic here. I might find it (having trouble finding what runs `_printBanner()`, but if you find it first that's cool too.

**Comment by mikemaccana** [comment]
Oh it's `series` which is a pre-promises flow control tool. `_checkArc()` fails, but it goes on to run `_printBanner()` anyway. Debugging...

**Comment by mikemaccana** [comment]
Looks like `utils.readArc()` has some kind of sync issue. Replacing it with something that always throws stops it continuing.

![image](https://user-images.githubusercontent.com/172594/63018724-7a208e00-be91-11e9-83eb-bcb1fe2e6c9a.png)

**Comment by ryanblock** [comment]
I don't think this is still an issue, please reopen if it's causing further problems though!
