### ISSUE TITLE
inconsistencies of GSI names between staging and testing

### ISSUE THREAD

**Issue by eshikerya** [architect/sandbox#45]
**Describe the issue**
After deploy GSI named like ```partitionKey-index```/```partitionKey-rangeKey-index```.
But testing DB creating in arc@5 scheme ```tableName-stage-partitionKey-index```

```javascript
// src/db/create-table/_get-global-secondary-index.js
// line 12
var IndexName = hasOne? `${name}-${keys[0]}-index` : `${name}-${keys[0]}-${keys[1]}-index`
```

is there anyway to determine arc@5 or arc@6 is running?
so we could generate ```indexName``` accordingly

**Comment by ryanblock** [comment]
This issue is incomplete (please refer to the new issue template); can you please more fully describe what's going on, the differences in behavior you're seeing, etc.?

**Comment by eshikerya** [comment]
in ARC6 you guys changed the naming scheme in dynamoDB. earlier the index name created by scheme: ```${TableName}-${stage}-${indexName}-index```
in ARC6 index name is index name + suffix.
so in case you try to work with GSI in ARC6 sandbox you will get “index not found” error.
My PR is fixing this issue

**Comment by ryanblock** [comment]
Hmm, doesn't sound familiar, I don't believe that was explicit although it's possible that changed with arc/functions or data.

Again, per the new issue template, please post reproduction steps (and if possible a use case in code) so I can see what behavior you're experiencing, and I'll happily take a look. More information / steps is better than less. Thanks!

**Comment by eshikerya** [comment]
ok. here is how to reproduce:
1. ```mkdir test-arc && cd test-arc && arc init```
2. open ```.arc```, it should looks like this:
```
@app
test

@http
get /

@tables
table
  key *Number

@indexes
table
  idx *Number
```
3. now lets modify our handler:
```javascript
const arc = require("@architect/functions");
exports.handler = async function http(req) {
  const db = await arc.tables();
  Promise.all(
    [1, 2, 3, 4, 5, 6].map(id => {
      return db.table.put({
        key: id,
        idx: id % 2
      });
    })
  );
  const r = await db.table.query({
    // this is the index name im talking about
    // when you deploy it to AWS, the index name will be "idx-index"
    IndexName: "test-staging-table-idx-index",
    KeyConditionExpression: "idx = :field",
    ExpressionAttributeValues: {
      ":field": 1
    }
  });

  return {
    headers: { "content-type": "text/html; charset=utf8" },
    body: JSON.stringify(r.Items)
  };
};
```
4. start sandbox
5. open browser and out page ```http://localhost:3333```
6. see the result: ```[{"key":3,"idx":1},{"key":1,"idx":1},{"key":5,"idx":1}]```
7. deploy to aws, check GSI index name created for table in dynamoDB, it would be ```idx-index```

**Comment by eshikerya** [comment]
@ryanblock here is repository with code to reproduce: https://github.com/eshikerya/arc.sandbox.issue.git

**Comment by ryanblock** [comment]
Rad, thank you! Will take a look today. 🌈

**Comment by eshikerya** [comment]
@ryanblock BTW, I have to say, the index name created for AWS, the ```idx-name``` is nice, it should be like this. because with ARC@5 I had to create something like this:
```javascript
const r = await db.table.query({
  IndexName: `test-${process.env.NODE_ENV}-table-idx-index`,
```
and do it allover, again and again... then I get an idea to extend method returning access to the methods get/put/query with method returns actual table name... and in next 30 minutes ARC@6 was released:)

another thing I'd like to add: to move all request boilerplate with IndexName/KeyConditionExpression/etc under ```db.table.getIndex({idx: value, idx2: value2})```
for cases where you need full control on query parameters - we have ```query()``` method...
I could make PR for it

**Comment by ryanblock** [comment]
Ok, was able to dig further into it – thanks for those repro steps, def helpful. 

This issue goes far deeper than what you're seeing in sandbox, and relates to the way in which we're generating both tables and indexes, within and outside the world of CloudFormation.

I'm going to have to discuss further with @brianleroux, will do so tomorrow and see if we can formulate a plan on how to proceed.

In the mean time re. request boilerplate, let's try to keep issues individually scoped please – feel free to open up a feature request (although I think what you're describing is in architect/functions).

**Comment by brianleroux** [comment]
update for this thread we have a fix coming. currently published in `@architect/sandbox@RC` thanks for the patience all
