### ISSUE TITLE
`{ cookie, status: 302, location: url }` still works with `arc sandbox`

### ISSUE THREAD

**Issue by gr2m** [architect/sandbox#49]
follow up for slack discussion with @brianleroux  https://architecture-as-text.slack.com/archives/C6BGT0D08/p1566611096267800?thread_ts=1566604233.263200&cid=C6BGT0D08

**Describe the issue**

With version 6, this no longer works in http functions when deploying

```js
return { status: 302, cookie, location: url }
```

Instead, headers have to be defined explicitly. And `status` is now `statusCode`

```js
return { statusCode: 302, headers: { 'set-cookie': cookie, location: url } }
```

**Comment by ryanblock** [comment]
Hey, this issue is pretty fuzzy. I caught up with the conversation in Slack, it sounds like the requested remedy is for Sandbox in Arc 6 to fail if not given Arc 6-specific params, so as to prevent drift and diff expectations between Sandbox and AWS? Is there more to it?

**Comment by gr2m** [comment]
That sums it up. Ideally I'd expect `arc sandbox` to throw an error with hints how to migrate to the new format

**Comment by ryanblock** [comment]
That’s legit, will impl this ASAP!
