### ISSUE TITLE
static proxy at root not working for global installs 

### ISSUE THREAD

**Issue by brianleroux** [architect/sandbox#92]
as of `6.0.13`

1. clone `https://github.com/andybee/arc-static`
2. `arc sandbox`

<img width="300" alt="Screen Shot 2019-10-10 at 11 34 16 AM" src="https://user-images.githubusercontent.com/990/66583831-e093f680-eb38-11e9-8075-027862c95237.png">

workaround here: 
https://gist.github.com/brianleroux/9fc2bcb29f96a29022ac918385727f1e

(going to duplicate this bug for folks looking for a fix in the architect/architect repo)

**Comment by ryanblock** [comment]
**Describe the issue**
The following arc file produces a `Requested function is missing` error with arc globally installed:

```
@app
arc-static

@static

@http
```

**Comment by ryanblock** [comment]
Per @grahamb:
> I was just about to open an issue for the same problem. Sample repo: https://github.com/grahamb/arc-public-directory-issue

**Comment by ryanblock** [comment]
Now live in Sandbox `1.4.5` and Architect `6.0.14@RC.3`; `npm i -g @architect/architect@RC` and let me know how it does for ya. Assuming all is well (tested out good here), should go out this week in `6.0.14`.

**Comment by grahamb** [comment]
Everything looks good on 6.0.14@RC.3. Thanks for the speedy fix, @ryanblock!
