### ISSUE TITLE
`Requested function is missing` error with empty @static + @http

### ISSUE THREAD

**Issue by ryanblock** [architect/sandbox#93]
**Describe the issue**
The following arc file produces a `Requested function is missing` error:

```
@app
arc-static

@static

@http
```

**Comment by grahamb** [comment]
I was just about to open an issue for the same problem. Sample repo: https://github.com/grahamb/arc-public-directory-issue

**Comment by ryanblock** [comment]
Dupe of #92, closing in favor of that
